### ISSUE TITLE
Colin Wilson v1.0 issue

### ISSUE THREAD

**Issue by leakyzinc** [colinwilson/kemp-esp-custom-forms#2]
Thanks for these templates, much better than the default Kemp ones.

Have tried to use the Colin Wilson v1.0 template (heavily modified one).  Packaged up in to a tar, uploaded to the Loadmaster and specified the image set in my ESP option.  Form appears and accepts my username and password after clicking Log On, asks for passphrase which I enter and then nothing.  Log On button appears to do nothing on the passphrase step.

SSO is working on my Loadmaster with either the default SSO image set or a custom basic one downloaded from Kemp.  Tried using Chrome and Edge.  My LM is on version 7.2.56.0.21331.RELEASE (which is the GA I think).

Any ideas?  Thanks.

EDIT: If I change the javascript so that the username field is always shown and I reenter the username along with the passphrase on that step it then works.

SOLVED: Javascript required the additional of the following so that the hidden username text box didn't require a value the second time round;

tmp = document.getElementById("username");
tmp.required = false;

Place at the end of switch (curlmode) switch 7

**Comment by colinwilson** [comment]
Glad you managed to resolve this. 👍 . And thanks for making edits to include the solution.
